MODNAME="DexOptimizer"
DEVNAME="Magellan, ZerxFox, Гоша"
MODREQ="Android 9+ & Magisk 23+"
DEVLINK="@ZerxFox"
LINKPUB="t.me/magiskksuapatchhub"

echo " | Модуль: $MODNAME"
echo " |"
echo " | Информационный блок"
echo " |"
echo " | Этот модуль повышает производительность,"
echo " | экономит ресурсы и сокращает"
echo " | время запуска приложений"
echo " | установите модуль Bootloop Protector"
echo " |"
echo " | • Разработчик:       $DEVNAME"
echo " | • Требования:        $MODREQ"
echo " | • Telegram:          $DEVLINK"
echo " |"
echo " | Отдельная благодарность за помощь в тестировании"
echo " | @lowriddr, @OlegVapnik, @venlys"
echo " |"
echo " | TG-канал: $LINKPUB"
echo ""
echo ""